wandb_version: 1

policy_type:
  desc: null
  value: MlpPolicy
total_timesteps:
  desc: null
  value: 2000000
env_id:
  desc: null
  value: <TimeLimit<RLBenchEnv<teodor_extract_with_distractors_scrambled-state-v0>>>
n_steps:
  desc: null
  value: 500
ent_coef:
  desc: null
  value: 0.01
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714062947.949237
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 22
      - 23
      - 35
      4: 3.10.12
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
algo:
  desc: null
  value: PPO
policy_class:
  desc: null
  value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
device:
  desc: null
  value: cpu
verbose:
  desc: null
  value: 1
policy_kwargs:
  desc: null
  value: '{}'
num_timesteps:
  desc: null
  value: 0
_total_timesteps:
  desc: null
  value: 2000000
_num_timesteps_at_start:
  desc: null
  value: 0
seed:
  desc: null
  value: None
action_noise:
  desc: null
  value: None
start_time:
  desc: null
  value: 1714062949570757634
learning_rate:
  desc: null
  value: 0.0003
tensorboard_log:
  desc: null
  value: runs/qys4u4s5
_last_obs:
  desc: null
  value: "[[ 1.00000000e+00 -1.43051147e-05  2.50816345e-03 -2.00271606e-04\n  -2.43186951e-04\
    \  2.52723694e-04  6.72340393e-04 -1.28746033e-04\n   1.67250801e-06  1.75482303e-01\
    \ -7.83476298e-06 -8.73208702e-01\n   2.01514849e-05  1.22133040e+00  7.85391212e-01\
    \ -3.09233777e-02\n   2.36824932e+01 -5.68813197e-02 -1.60907040e+01 -1.61639750e-01\n\
    \  -4.33309269e+00  2.25797053e-02  2.78607398e-01 -8.16041231e-03\n   1.47164857e+00\
    \ -1.18043818e-06  9.92710054e-01 -5.38022391e-07\n   1.20527044e-01  4.00018170e-02\
    \  3.99986506e-02  1.77935208e-03\n  -4.37369948e-04  3.87579212e-06  1.77886186e-03\
    \  4.36601054e-04\n  -4.00394219e-06  1.25698388e-01 -2.23279431e-01  7.74995863e-01\n\
    \   2.50000000e-01  0.00000000e+00  7.51999855e-01  3.94517601e-01\n  -2.05309585e-01\
    \  7.75002837e-01  1.08442828e-01  2.06409693e-01\n   7.74994910e-01  2.54127562e-01\
    \  1.38700247e-01  7.64987350e-01\n   4.10388082e-01  1.96542010e-01  7.75003195e-01\
    \  1.24895021e-01\n  -9.41570327e-02  8.76999557e-01  2.50000000e-01  0.00000000e+00\n\
    \   1.15199983e+00]]"
_last_episode_starts:
  desc: null
  value: '[ True]'
_last_original_obs:
  desc: null
  value: None
_episode_num:
  desc: null
  value: 0
use_sde:
  desc: null
  value: 'False'
sde_sample_freq:
  desc: null
  value: -1
_current_progress_remaining:
  desc: null
  value: 1.0
_stats_window_size:
  desc: null
  value: 100
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
_n_updates:
  desc: null
  value: 0
_custom_logger:
  desc: null
  value: 'False'
env:
  desc: null
  value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x7f51f01520e0>
_vec_normalize_env:
  desc: null
  value: None
observation_space:
  desc: null
  value: Box(-inf, inf, (61,), float32)
action_space:
  desc: null
  value: Box(-1.0, 1.0, (8,), float32)
n_envs:
  desc: null
  value: 1
gamma:
  desc: null
  value: 0.99
gae_lambda:
  desc: null
  value: 0.95
vf_coef:
  desc: null
  value: 0.5
max_grad_norm:
  desc: null
  value: 0.5
rollout_buffer_class:
  desc: null
  value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
  desc: null
  value: '{}'
batch_size:
  desc: null
  value: 64
n_epochs:
  desc: null
  value: 10
clip_range:
  desc: null
  value: <function constant_fn.<locals>.func at 0x7f51f00cbe20>
clip_range_vf:
  desc: null
  value: None
normalize_advantage:
  desc: null
  value: 'True'
target_kl:
  desc: null
  value: None
lr_schedule:
  desc: null
  value: <function constant_fn.<locals>.func at 0x7f51f016d360>
rollout_buffer:
  desc: null
  value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x7f51f01525f0>
policy:
  desc: null
  value: "ActorCriticPolicy(\n  (features_extractor): FlattenExtractor(\n    (flatten):\
    \ Flatten(start_dim=1, end_dim=-1)\n  )\n  (pi_features_extractor): FlattenExtractor(\n\
    \    (flatten): Flatten(start_dim=1, end_dim=-1)\n  )\n  (vf_features_extractor):\
    \ FlattenExtractor(\n    (flatten): Flatten(start_dim=1, end_dim=-1)\n  )\n  (mlp_extractor):\
    \ MlpExtractor(\n    (policy_net): Sequential(\n      (0): Linear(in_features=61,\
    \ out_features=64, bias=True)\n      (1): Tanh()\n      (2): Linear(in_features=64,\
    \ out_features=64, bias=True)\n      (3): Tanh()\n    )\n    (value_net): Sequential(\n\
    \      (0): Linear(in_features=61, out_features=64, bias=True)\n      (1): Tanh()\n\
    \      (2): Linear(in_features=64, out_features=64, bias=True)\n      (3): Tanh()\n\
    \    )\n  )\n  (action_net): Linear(in_features=64, out_features=8, bias=True)\n\
    \  (value_net): Linear(in_features=64, out_features=1, bias=True)\n)"
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x7f521b6eda20>
