wandb_version: 1

policy_type:
  desc: null
  value: MlpPolicy
total_timesteps:
  desc: null
  value: 500000
env_id:
  desc: null
  value: <OrderEnforcing<RLBenchEnv<close_grill-state-v0>>>
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1707931116.374151
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 3
      - 16
      - 22
      - 23
      - 35
      4: 3.10.12
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
algo:
  desc: null
  value: PPO
policy_class:
  desc: null
  value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
device:
  desc: null
  value: cpu
verbose:
  desc: null
  value: 1
policy_kwargs:
  desc: null
  value: '{}'
num_timesteps:
  desc: null
  value: 0
_total_timesteps:
  desc: null
  value: 500000
_num_timesteps_at_start:
  desc: null
  value: 0
seed:
  desc: null
  value: None
action_noise:
  desc: null
  value: None
start_time:
  desc: null
  value: 1707931117573754924
learning_rate:
  desc: null
  value: 0.0003
tensorboard_log:
  desc: null
  value: runs/addvaa6z
_last_obs:
  desc: null
  value: "[[ 1.00000000e+00 -2.86102295e-05 -2.44617462e-03  1.81198120e-04\n   2.43186951e-03\
    \ -1.28746033e-04 -5.53131104e-04  2.38418579e-05\n  -9.29474663e-06  1.75569803e-01\
    \  9.80821187e-06 -8.73202264e-01\n   8.46897274e-06  1.22136641e+00  7.85390735e-01\
    \  3.18619460e-02\n   2.38594093e+01 -6.74162060e-04 -1.62034645e+01 -1.38835520e-01\n\
    \  -4.35022545e+00  3.23973075e-02  2.78653353e-01 -8.16328265e-03\n   1.47157609e+00\
    \ -6.73790680e-07  9.92715359e-01 -3.48473031e-06\n   1.20483369e-01  3.99953648e-02\
    \  4.00070697e-02  1.78620219e-03\n  -4.34717542e-04 -3.53902578e-06  1.78554654e-03\
    \  4.34991729e-04\n   4.06652680e-06  3.02950054e-01  2.45167494e-01  7.51999855e-01\n\
    \   0.00000000e+00  0.00000000e+00 -6.31650388e-01  7.75253415e-01\n   3.23153645e-01\
    \  1.47229582e-01  9.06679511e-01  0.00000000e+00\n   0.00000000e+00  1.01555496e-01\
    \  9.94829893e-01  3.21880966e-01\n   1.53093234e-01  8.80526245e-01  4.48999316e-01\
    \  5.46214342e-01\n   5.46268404e-01  4.49043840e-01  2.28640527e-01  3.16120759e-02\n\
    \   1.04541934e+00 -7.02275932e-01  5.58747537e-02  6.82379544e-01\n  -1.95050657e-01\
    \  0.00000000e+00  1.81882858e-01  2.64032662e-01\n   1.07366276e+00  5.24522305e-01\
    \ -4.25782204e-01  5.68906784e-01\n   4.68968093e-01  1.98757857e-01  1.23097211e-01\
    \  1.02467632e+00\n   7.03455687e-01  7.17936978e-02  7.03449845e-01 -7.17930496e-02\n\
    \   2.25677192e-01  5.12859300e-02  1.17687201e+00  6.46144509e-01\n  -2.93726981e-01\
    \  5.70954084e-01 -4.12593305e-01  2.11536855e-01\n   1.24135375e-01  1.26485085e+00\
    \  9.79860067e-01  9.85099971e-02\n   1.35467779e-02  1.73166364e-01  2.28003010e-01\
    \  3.82596329e-02\n   1.15777457e+00  6.46528125e-01 -2.92898566e-01  5.71534216e-01\n\
    \  -4.11777198e-01  2.05534086e-01  1.40119731e-01  1.30246437e+00\n   9.79860067e-01\
    \  9.85100046e-02  1.35466047e-02  1.73166320e-01\n   2.12986916e-01  1.16722740e-01\
    \  1.24592841e+00  6.19744658e-01\n  -3.46002966e-01  5.35073817e-01 -4.58142519e-01]]"
_last_episode_starts:
  desc: null
  value: '[ True]'
_last_original_obs:
  desc: null
  value: None
_episode_num:
  desc: null
  value: 0
use_sde:
  desc: null
  value: 'False'
sde_sample_freq:
  desc: null
  value: -1
_current_progress_remaining:
  desc: null
  value: 1.0
_stats_window_size:
  desc: null
  value: 100
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
_n_updates:
  desc: null
  value: 0
_custom_logger:
  desc: null
  value: 'False'
env:
  desc: null
  value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x7f1e5419eec0>
_vec_normalize_env:
  desc: null
  value: None
observation_space:
  desc: null
  value: Box(-inf, inf, (115,), float32)
action_space:
  desc: null
  value: Box(-1.0, 1.0, (8,), float32)
n_envs:
  desc: null
  value: 1
n_steps:
  desc: null
  value: 2048
gamma:
  desc: null
  value: 0.99
gae_lambda:
  desc: null
  value: 0.95
ent_coef:
  desc: null
  value: 0.0
vf_coef:
  desc: null
  value: 0.5
max_grad_norm:
  desc: null
  value: 0.5
rollout_buffer_class:
  desc: null
  value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
  desc: null
  value: '{}'
batch_size:
  desc: null
  value: 64
n_epochs:
  desc: null
  value: 10
clip_range:
  desc: null
  value: <function constant_fn.<locals>.func at 0x7f1e78985a20>
clip_range_vf:
  desc: null
  value: None
normalize_advantage:
  desc: null
  value: 'True'
target_kl:
  desc: null
  value: None
lr_schedule:
  desc: null
  value: <function constant_fn.<locals>.func at 0x7f1e78985b40>
rollout_buffer:
  desc: null
  value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x7f1e5419e9b0>
policy:
  desc: null
  value: "ActorCriticPolicy(\n  (features_extractor): FlattenExtractor(\n    (flatten):\
    \ Flatten(start_dim=1, end_dim=-1)\n  )\n  (pi_features_extractor): FlattenExtractor(\n\
    \    (flatten): Flatten(start_dim=1, end_dim=-1)\n  )\n  (vf_features_extractor):\
    \ FlattenExtractor(\n    (flatten): Flatten(start_dim=1, end_dim=-1)\n  )\n  (mlp_extractor):\
    \ MlpExtractor(\n    (policy_net): Sequential(\n      (0): Linear(in_features=115,\
    \ out_features=64, bias=True)\n      (1): Tanh()\n      (2): Linear(in_features=64,\
    \ out_features=64, bias=True)\n      (3): Tanh()\n    )\n    (value_net): Sequential(\n\
    \      (0): Linear(in_features=115, out_features=64, bias=True)\n      (1): Tanh()\n\
    \      (2): Linear(in_features=64, out_features=64, bias=True)\n      (3): Tanh()\n\
    \    )\n  )\n  (action_net): Linear(in_features=64, out_features=8, bias=True)\n\
    \  (value_net): Linear(in_features=64, out_features=1, bias=True)\n)"
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x7f1e788a9e70>
