wandb_version: 1

policy_type:
  desc: null
  value: MlpPolicy
total_timesteps:
  desc: null
  value: 2000000
env_id:
  desc: null
  value: <TimeLimit<RLBenchEnv<teodor_extract_with_distractors_scrambled-state-v0>>>
n_steps:
  desc: null
  value: 500
ent_coef:
  desc: null
  value: 0.01
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714063471.889712
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 16
      - 22
      - 23
      - 35
      4: 3.10.12
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
algo:
  desc: null
  value: PPO
policy_class:
  desc: null
  value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
device:
  desc: null
  value: cuda
verbose:
  desc: null
  value: 1
policy_kwargs:
  desc: null
  value: '{}'
num_timesteps:
  desc: null
  value: 0
_total_timesteps:
  desc: null
  value: 2000000
_num_timesteps_at_start:
  desc: null
  value: 0
seed:
  desc: null
  value: None
action_noise:
  desc: null
  value: None
start_time:
  desc: null
  value: 1714063472958320926
learning_rate:
  desc: null
  value: 0.0003
tensorboard_log:
  desc: null
  value: runs/nwnr1fws
_last_obs:
  desc: null
  value: "[[ 1.0000000e+00 -8.1062317e-05  5.2070618e-03  2.2888184e-04\n   2.3889542e-03\
    \  1.1920929e-04  1.8119812e-04 -2.1934509e-04\n  -2.3806078e-06  1.7555025e-01\
    \ -1.4272064e-05 -8.7324947e-01\n   6.8000427e-06  1.2213774e+00  7.8538573e-01\
    \  2.3355346e-02\n   2.3616842e+01 -1.5791457e-02 -1.6056276e+01 -1.4088669e-01\n\
    \  -4.3138704e+00  3.3501975e-02  2.7862722e-01 -8.1510711e-03\n   1.4716241e+00\
    \  4.8849586e-07  9.9271244e-01 -2.9520108e-06\n   1.2050763e-01  3.9999940e-02\
    \  4.0000800e-02  1.7803193e-03\n  -4.3740420e-04 -2.3275613e-06  1.7796695e-03\
    \  4.3787807e-04\n   2.0712614e-06  4.6072316e-01 -1.3457616e-01  7.7500427e-01\n\
    \   2.5000000e-01  0.0000000e+00  7.5199986e-01  3.6991590e-01\n   8.1291065e-02\
    \  7.6412809e-01  1.5146607e-01 -6.7742459e-02\n   7.6300412e-01  4.9769244e-01\
    \  4.6482153e-02  7.7500558e-01\n   8.6340487e-02  1.2546440e-02  7.5998878e-01\
    \  3.3457604e-01\n  -6.4054385e-02  8.7699968e-01  2.5000000e-01  0.0000000e+00\n\
    \   1.1519998e+00]]"
_last_episode_starts:
  desc: null
  value: '[ True]'
_last_original_obs:
  desc: null
  value: None
_episode_num:
  desc: null
  value: 0
use_sde:
  desc: null
  value: 'False'
sde_sample_freq:
  desc: null
  value: -1
_current_progress_remaining:
  desc: null
  value: 1.0
_stats_window_size:
  desc: null
  value: 100
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
_n_updates:
  desc: null
  value: 0
_custom_logger:
  desc: null
  value: 'False'
env:
  desc: null
  value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x7ea90273b2e0>
_vec_normalize_env:
  desc: null
  value: None
observation_space:
  desc: null
  value: Box(-inf, inf, (61,), float32)
action_space:
  desc: null
  value: Box(-1.0, 1.0, (8,), float32)
n_envs:
  desc: null
  value: 1
gamma:
  desc: null
  value: 0.99
gae_lambda:
  desc: null
  value: 0.95
vf_coef:
  desc: null
  value: 0.5
max_grad_norm:
  desc: null
  value: 0.5
rollout_buffer_class:
  desc: null
  value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
  desc: null
  value: '{}'
batch_size:
  desc: null
  value: 64
n_epochs:
  desc: null
  value: 10
clip_range:
  desc: null
  value: <function constant_fn.<locals>.func at 0x7ea90273dcf0>
clip_range_vf:
  desc: null
  value: None
normalize_advantage:
  desc: null
  value: 'True'
target_kl:
  desc: null
  value: None
lr_schedule:
  desc: null
  value: <function constant_fn.<locals>.func at 0x7ea90273c820>
rollout_buffer:
  desc: null
  value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x7ea90273b130>
policy:
  desc: null
  value: "ActorCriticPolicy(\n  (features_extractor): FlattenExtractor(\n    (flatten):\
    \ Flatten(start_dim=1, end_dim=-1)\n  )\n  (pi_features_extractor): FlattenExtractor(\n\
    \    (flatten): Flatten(start_dim=1, end_dim=-1)\n  )\n  (vf_features_extractor):\
    \ FlattenExtractor(\n    (flatten): Flatten(start_dim=1, end_dim=-1)\n  )\n  (mlp_extractor):\
    \ MlpExtractor(\n    (policy_net): Sequential(\n      (0): Linear(in_features=61,\
    \ out_features=64, bias=True)\n      (1): Tanh()\n      (2): Linear(in_features=64,\
    \ out_features=64, bias=True)\n      (3): Tanh()\n    )\n    (value_net): Sequential(\n\
    \      (0): Linear(in_features=61, out_features=64, bias=True)\n      (1): Tanh()\n\
    \      (2): Linear(in_features=64, out_features=64, bias=True)\n      (3): Tanh()\n\
    \    )\n  )\n  (action_net): Linear(in_features=64, out_features=8, bias=True)\n\
    \  (value_net): Linear(in_features=64, out_features=1, bias=True)\n)"
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x7ea91c3a34c0>
