wandb_version: 1

policy_type:
  desc: null
  value: MlpPolicy
total_timesteps:
  desc: null
  value: 1000000
env_id:
  desc: null
  value: <TimeLimit<RLBenchEnv<teodor_zone_pick_and_place-state-v0>>>
n_steps:
  desc: null
  value: 200
ent_coef:
  desc: null
  value: 0.01
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1713260628.447607
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 22
      - 23
      - 35
      4: 3.10.12
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
algo:
  desc: null
  value: PPO
policy_class:
  desc: null
  value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
device:
  desc: null
  value: cpu
verbose:
  desc: null
  value: 1
policy_kwargs:
  desc: null
  value: '{}'
num_timesteps:
  desc: null
  value: 0
_total_timesteps:
  desc: null
  value: 1000000
_num_timesteps_at_start:
  desc: null
  value: 0
seed:
  desc: null
  value: None
action_noise:
  desc: null
  value: None
start_time:
  desc: null
  value: 1713260629724050345
learning_rate:
  desc: null
  value: 0.0003
tensorboard_log:
  desc: null
  value: runs/t5fxw4r2
_last_obs:
  desc: null
  value: "[[ 1.0000000e+00  4.7683716e-06  4.3153763e-03 -2.5272369e-04\n  -1.0633469e-03\
    \ -1.4305115e-05 -7.0571899e-04 -9.0599060e-05\n   3.5779522e-09  1.7540863e-01\
    \ -1.4748901e-05 -8.7314624e-01\n  -8.2935185e-07  1.2215302e+00  7.8540170e-01\
    \ -7.0425896e-03\n   2.3283184e+01 -3.8689710e-02 -1.5835660e+01 -1.6001000e-01\n\
    \  -4.2418594e+00  2.5236037e-02  2.7848566e-01 -8.1740227e-03\n   1.4719583e+00\
    \  1.3229026e-06  9.9266630e-01 -4.3377927e-06\n   1.2088719e-01  3.9997332e-02\
    \  4.0001284e-02  1.7653375e-03\n  -4.4472964e-04  1.4990568e-06  1.7673105e-03\
    \  4.4398606e-04\n  -1.1861324e-06  2.4999933e-01 -3.0307838e-08  7.7499896e-01\n\
    \   2.5000000e-01  0.0000000e+00  7.5199986e-01]]"
_last_episode_starts:
  desc: null
  value: '[ True]'
_last_original_obs:
  desc: null
  value: None
_episode_num:
  desc: null
  value: 0
use_sde:
  desc: null
  value: 'False'
sde_sample_freq:
  desc: null
  value: -1
_current_progress_remaining:
  desc: null
  value: 1.0
_stats_window_size:
  desc: null
  value: 100
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
_n_updates:
  desc: null
  value: 0
_custom_logger:
  desc: null
  value: 'False'
env:
  desc: null
  value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x7fec38bf3ca0>
_vec_normalize_env:
  desc: null
  value: None
observation_space:
  desc: null
  value: Box(-inf, inf, (43,), float32)
action_space:
  desc: null
  value: Box(-1.0, 1.0, (8,), float32)
n_envs:
  desc: null
  value: 1
gamma:
  desc: null
  value: 0.99
gae_lambda:
  desc: null
  value: 0.95
vf_coef:
  desc: null
  value: 0.5
max_grad_norm:
  desc: null
  value: 0.5
rollout_buffer_class:
  desc: null
  value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
  desc: null
  value: '{}'
batch_size:
  desc: null
  value: 64
n_epochs:
  desc: null
  value: 10
clip_range:
  desc: null
  value: <function constant_fn.<locals>.func at 0x7fec38beb370>
clip_range_vf:
  desc: null
  value: None
normalize_advantage:
  desc: null
  value: 'True'
target_kl:
  desc: null
  value: None
lr_schedule:
  desc: null
  value: <function constant_fn.<locals>.func at 0x7fec38c3c8b0>
rollout_buffer:
  desc: null
  value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x7fec38bf3dc0>
policy:
  desc: null
  value: "ActorCriticPolicy(\n  (features_extractor): FlattenExtractor(\n    (flatten):\
    \ Flatten(start_dim=1, end_dim=-1)\n  )\n  (pi_features_extractor): FlattenExtractor(\n\
    \    (flatten): Flatten(start_dim=1, end_dim=-1)\n  )\n  (vf_features_extractor):\
    \ FlattenExtractor(\n    (flatten): Flatten(start_dim=1, end_dim=-1)\n  )\n  (mlp_extractor):\
    \ MlpExtractor(\n    (policy_net): Sequential(\n      (0): Linear(in_features=43,\
    \ out_features=64, bias=True)\n      (1): Tanh()\n      (2): Linear(in_features=64,\
    \ out_features=64, bias=True)\n      (3): Tanh()\n    )\n    (value_net): Sequential(\n\
    \      (0): Linear(in_features=43, out_features=64, bias=True)\n      (1): Tanh()\n\
    \      (2): Linear(in_features=64, out_features=64, bias=True)\n      (3): Tanh()\n\
    \    )\n  )\n  (action_net): Linear(in_features=64, out_features=8, bias=True)\n\
    \  (value_net): Linear(in_features=64, out_features=1, bias=True)\n)"
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x7fec5e8bc550>
