wandb_version: 1

policy_type:
  desc: null
  value: MlpPolicy
total_timesteps:
  desc: null
  value: 2000000
env_id:
  desc: null
  value: <TimeLimit<RLBenchEnv<slide_block_to_target-state-v0>>>
n_steps:
  desc: null
  value: 180
ent_coef:
  desc: null
  value: 0.01
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1710934866.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 3
      - 16
      - 22
      - 23
      - 35
      4: 3.10.12
      5: 0.16.4
      8:
      - 5
      13: linux-x86_64
algo:
  desc: null
  value: PPO
policy_class:
  desc: null
  value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
device:
  desc: null
  value: cpu
verbose:
  desc: null
  value: 1
policy_kwargs:
  desc: null
  value: '{}'
num_timesteps:
  desc: null
  value: 0
_total_timesteps:
  desc: null
  value: 2000000
_num_timesteps_at_start:
  desc: null
  value: 0
seed:
  desc: null
  value: None
action_noise:
  desc: null
  value: None
start_time:
  desc: null
  value: 1710934873563298699
learning_rate:
  desc: null
  value: 0.0003
tensorboard_log:
  desc: null
  value: runs/92vc5nvw
_last_obs:
  desc: null
  value: "[[ 1.00000000e+00 -1.00135803e-04  5.50746918e-03 -9.53674316e-06\n  -3.20911407e-03\
    \ -1.57356262e-04 -4.62532043e-04 -1.04904175e-04\n  -5.71846795e-06  1.75626069e-01\
    \ -4.97373912e-06 -8.73398244e-01\n   5.60794979e-06  1.22132540e+00  7.85380721e-01\
    \  9.24727134e-03\n   2.29171791e+01 -3.90776172e-02 -1.55985384e+01 -1.49417803e-01\n\
    \  -4.15055037e+00  2.54519340e-02  2.78619707e-01 -8.16262513e-03\n   1.47162199e+00\
    \ -1.18043624e-06  9.92711961e-01 -8.72633521e-08\n   1.20511845e-01  3.99998203e-02\
    \  4.00018282e-02  1.75562501e-03\n  -4.49272979e-04  1.29342084e-06  1.75623596e-03\
    \  4.49329615e-04\n  -1.95205212e-06  2.74996400e-01 -2.50000320e-02  7.78124630e-01\n\
    \   2.74999857e-01  1.49999946e-01  7.53000200e-01]]"
_last_episode_starts:
  desc: null
  value: '[ True]'
_last_original_obs:
  desc: null
  value: None
_episode_num:
  desc: null
  value: 0
use_sde:
  desc: null
  value: 'False'
sde_sample_freq:
  desc: null
  value: -1
_current_progress_remaining:
  desc: null
  value: 1.0
_stats_window_size:
  desc: null
  value: 100
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
_n_updates:
  desc: null
  value: 0
_custom_logger:
  desc: null
  value: 'False'
env:
  desc: null
  value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x703573520130>
_vec_normalize_env:
  desc: null
  value: None
observation_space:
  desc: null
  value: Box(-inf, inf, (43,), float32)
action_space:
  desc: null
  value: Box(-1.0, 1.0, (8,), float32)
n_envs:
  desc: null
  value: 1
gamma:
  desc: null
  value: 0.99
gae_lambda:
  desc: null
  value: 0.95
vf_coef:
  desc: null
  value: 0.5
max_grad_norm:
  desc: null
  value: 0.5
rollout_buffer_class:
  desc: null
  value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
  desc: null
  value: '{}'
batch_size:
  desc: null
  value: 64
n_epochs:
  desc: null
  value: 10
clip_range:
  desc: null
  value: <function constant_fn.<locals>.func at 0x7035745dd870>
clip_range_vf:
  desc: null
  value: None
normalize_advantage:
  desc: null
  value: 'True'
target_kl:
  desc: null
  value: None
lr_schedule:
  desc: null
  value: <function constant_fn.<locals>.func at 0x7035745de950>
rollout_buffer:
  desc: null
  value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x703573520250>
policy:
  desc: null
  value: "ActorCriticPolicy(\n  (features_extractor): FlattenExtractor(\n    (flatten):\
    \ Flatten(start_dim=1, end_dim=-1)\n  )\n  (pi_features_extractor): FlattenExtractor(\n\
    \    (flatten): Flatten(start_dim=1, end_dim=-1)\n  )\n  (vf_features_extractor):\
    \ FlattenExtractor(\n    (flatten): Flatten(start_dim=1, end_dim=-1)\n  )\n  (mlp_extractor):\
    \ MlpExtractor(\n    (policy_net): Sequential(\n      (0): Linear(in_features=43,\
    \ out_features=64, bias=True)\n      (1): Tanh()\n      (2): Linear(in_features=64,\
    \ out_features=64, bias=True)\n      (3): Tanh()\n    )\n    (value_net): Sequential(\n\
    \      (0): Linear(in_features=43, out_features=64, bias=True)\n      (1): Tanh()\n\
    \      (2): Linear(in_features=64, out_features=64, bias=True)\n      (3): Tanh()\n\
    \    )\n  )\n  (action_net): Linear(in_features=64, out_features=8, bias=True)\n\
    \  (value_net): Linear(in_features=64, out_features=1, bias=True)\n)"
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x70359d98cf40>
