wandb_version: 1

policy_type:
  desc: null
  value: MlpPolicy
total_timesteps:
  desc: null
  value: 100000
env_id:
  desc: null
  value: <TimeLimit<RLBenchEnv<teodor_zone_pick_and_place-state-v0>>>
n_steps:
  desc: null
  value: 200
ent_coef:
  desc: null
  value: 0.01
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712661881.253149
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 22
      - 23
      - 35
      4: 3.10.12
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
algo:
  desc: null
  value: PPO
policy_class:
  desc: null
  value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
device:
  desc: null
  value: cpu
verbose:
  desc: null
  value: 1
policy_kwargs:
  desc: null
  value: '{}'
num_timesteps:
  desc: null
  value: 0
_total_timesteps:
  desc: null
  value: 100000
_num_timesteps_at_start:
  desc: null
  value: 0
seed:
  desc: null
  value: None
action_noise:
  desc: null
  value: None
start_time:
  desc: null
  value: 1712661882871962289
learning_rate:
  desc: null
  value: 0.0003
tensorboard_log:
  desc: null
  value: runs/sgkjz8h1
_last_obs:
  desc: null
  value: "[[ 1.0000000e+00  1.3351440e-04  3.1042099e-03  1.5258789e-04\n   5.0544739e-04\
    \ -2.1934509e-04  1.6212463e-04  3.6716461e-04\n   1.9109266e-06  1.7546871e-01\
    \ -7.1195063e-06 -8.7312478e-01\n   9.1842285e-06  1.2213080e+00  7.8538191e-01\
    \  3.2993652e-02\n   2.3284554e+01 -1.0640961e-02 -1.5824339e+01 -1.4163218e-01\n\
    \  -4.2275081e+00  2.3388037e-02  2.7858421e-01 -8.1642773e-03\n   1.4717166e+00\
    \ -7.9301509e-07  9.9270421e-01 -1.4767916e-06\n   1.2057557e-01  4.0000625e-02\
    \  3.9999027e-02  1.7654091e-03\n  -4.4206082e-04 -2.1532178e-06  1.7665208e-03\
    \  4.4229627e-04\n   2.0176171e-06  1.5733567e-01 -5.5170637e-02  7.7499646e-01\n\
    \   8.5915804e-02  1.6451977e-01  7.7499449e-01  3.0818290e-01\n  -7.8039393e-02\
    \  7.7500045e-01  2.5000000e-01  0.0000000e+00\n   7.5199986e-01  2.5000000e-01\
    \  0.0000000e+00  7.5199986e-01]]"
_last_episode_starts:
  desc: null
  value: '[ True]'
_last_original_obs:
  desc: null
  value: None
_episode_num:
  desc: null
  value: 0
use_sde:
  desc: null
  value: 'False'
sde_sample_freq:
  desc: null
  value: -1
_current_progress_remaining:
  desc: null
  value: 1.0
_stats_window_size:
  desc: null
  value: 100
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
_n_updates:
  desc: null
  value: 0
_custom_logger:
  desc: null
  value: 'False'
env:
  desc: null
  value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x7fd18c643d30>
_vec_normalize_env:
  desc: null
  value: None
observation_space:
  desc: null
  value: Box(-inf, inf, (52,), float32)
action_space:
  desc: null
  value: Box(-1.0, 1.0, (8,), float32)
n_envs:
  desc: null
  value: 1
gamma:
  desc: null
  value: 0.99
gae_lambda:
  desc: null
  value: 0.95
vf_coef:
  desc: null
  value: 0.5
max_grad_norm:
  desc: null
  value: 0.5
rollout_buffer_class:
  desc: null
  value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
  desc: null
  value: '{}'
batch_size:
  desc: null
  value: 64
n_epochs:
  desc: null
  value: 10
clip_range:
  desc: null
  value: <function constant_fn.<locals>.func at 0x7fd18c63b250>
clip_range_vf:
  desc: null
  value: None
normalize_advantage:
  desc: null
  value: 'True'
target_kl:
  desc: null
  value: None
lr_schedule:
  desc: null
  value: <function constant_fn.<locals>.func at 0x7fd18c48c790>
rollout_buffer:
  desc: null
  value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x7fd18c643e50>
policy:
  desc: null
  value: "ActorCriticPolicy(\n  (features_extractor): FlattenExtractor(\n    (flatten):\
    \ Flatten(start_dim=1, end_dim=-1)\n  )\n  (pi_features_extractor): FlattenExtractor(\n\
    \    (flatten): Flatten(start_dim=1, end_dim=-1)\n  )\n  (vf_features_extractor):\
    \ FlattenExtractor(\n    (flatten): Flatten(start_dim=1, end_dim=-1)\n  )\n  (mlp_extractor):\
    \ MlpExtractor(\n    (policy_net): Sequential(\n      (0): Linear(in_features=52,\
    \ out_features=64, bias=True)\n      (1): Tanh()\n      (2): Linear(in_features=64,\
    \ out_features=64, bias=True)\n      (3): Tanh()\n    )\n    (value_net): Sequential(\n\
    \      (0): Linear(in_features=52, out_features=64, bias=True)\n      (1): Tanh()\n\
    \      (2): Linear(in_features=64, out_features=64, bias=True)\n      (3): Tanh()\n\
    \    )\n  )\n  (action_net): Linear(in_features=64, out_features=8, bias=True)\n\
    \  (value_net): Linear(in_features=64, out_features=1, bias=True)\n)"
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x7fd18c6409d0>
